Document: beret
Title: Debian beret Manual
Author: <insert document author here>
Abstract: This manual describes what beret is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/beret/beret.sgml.gz

Format: postscript
Files: /usr/share/doc/beret/beret.ps.gz

Format: text
Files: /usr/share/doc/beret/beret.text.gz

Format: HTML
Index: /usr/share/doc/beret/html/index.html
Files: /usr/share/doc/beret/html/*.html
